// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lang.Core.Migrations
{
    [DbContext(typeof(LangDbContext))]
    [Migration("20221102235626_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lang.Core.Entity.FrequencyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrequencySource")
                        .HasColumnType("int");

                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("FrequencyData", (string)null);
                });

            modelBuilder.Entity("Lang.Core.Entity.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Lang.Core.Entity.WordList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WordLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Alfa"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Babel"
                        },
                        new
                        {
                            Id = 3,
                            Title = "2021"
                        },
                        new
                        {
                            Id = 4,
                            Title = "2022"
                        },
                        new
                        {
                            Id = 5,
                            Title = "2023"
                        },
                        new
                        {
                            Id = 6,
                            Title = "WON"
                        },
                        new
                        {
                            Id = 7,
                            Title = "REM"
                        });
                });

            modelBuilder.Entity("Lang.Core.Entity.WordListWord", b =>
                {
                    b.Property<int>("WordId")
                        .HasColumnType("int");

                    b.Property<int>("WordListId")
                        .HasColumnType("int");

                    b.HasKey("WordId", "WordListId");

                    b.HasIndex("WordListId");

                    b.ToTable("WordListWords");
                });

            modelBuilder.Entity("Lang.Core.Entity.FrequencyData", b =>
                {
                    b.HasOne("Lang.Core.Entity.Word", "Word")
                        .WithMany("FrequencyData")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");
                });

            modelBuilder.Entity("Lang.Core.Entity.WordListWord", b =>
                {
                    b.HasOne("Lang.Core.Entity.Word", "Word")
                        .WithMany("WordListWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lang.Core.Entity.WordList", "WordList")
                        .WithMany("WordListWords")
                        .HasForeignKey("WordListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Word");

                    b.Navigation("WordList");
                });

            modelBuilder.Entity("Lang.Core.Entity.Word", b =>
                {
                    b.Navigation("FrequencyData");

                    b.Navigation("WordListWords");
                });

            modelBuilder.Entity("Lang.Core.Entity.WordList", b =>
                {
                    b.Navigation("WordListWords");
                });
#pragma warning restore 612, 618
        }
    }
}
